system.path.root: D://Test/eslocal/

# 各类日志的保存地址
system.log.admin: D://Test/eslocal/administrator_operation.log
system.log.user:
system.log.system: D://Test/eslocal/monitorlog/
system.log.res: D://Test/eslocal/ruleStatistical.log